versatile_express: ca53x2: fix cpu node unit-address
Commit 4cf05447d0 ("versatile_express: Add Cortex-A53x2 SMM on V2M-1XV7
Device Tree") had a typo in the unit-address for one of the CPUs, which
can lead to dtc refusing to build the dtb unless forced to:

  dtc -I dts -O dtb -o vexpress-v2f-1xv7-ca53x2.dtb vexpress-v2f-1xv7-ca53x2.dts
  DTC: dts->dtb  on file "vexpress-v2f-1xv7-ca53x2.dts"
  ERROR (duplicate_node_names): Duplicate node name /cpus/cpu@0
  ERROR: Input tree has errors, aborting (use -f to force output)

This patch fixes up the unit-address for cpu@1 to correct this.

Signed-off-by: Mark Rutland <mark.rutland@arm.com>
Signed-off-by: Pawel Moll <pawel.moll@arm.com>